In [2]:
import numpy as np

In [16]:
def f(x,y,z):
    return 10*x+y+z    

In [247]:
np.fromfunction(lambda x,y: x+y ,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [249]:
np.fromfunction(lambda x,y: x==  y ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [17]:
a = np.fromfunction(f,(3,5,2),dtype=int)
a

array([[[ 0,  1],
        [ 1,  2],
        [ 2,  3],
        [ 3,  4],
        [ 4,  5]],

       [[10, 11],
        [11, 12],
        [12, 13],
        [13, 14],
        [14, 15]],

       [[20, 21],
        [21, 22],
        [22, 23],
        [23, 24],
        [24, 25]]])

In [18]:
type(a) #NumPy’s array class is called ndarray

numpy.ndarray

In [20]:
a[1,...]

array([[10, 11],
       [11, 12],
       [12, 13],
       [13, 14],
       [14, 15]])

In [21]:
a[...,0]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [23]:
np.floor(11.2222)

11.0

In [27]:
int(np.floor(11.2222))

11

### Shape Manipulation

In [34]:
np.random.random((3,4))

array([[0.76858639, 0.88681139, 0.92564685, 0.57904795],
       [0.58206973, 0.28177126, 0.454636  , 0.14931101],
       [0.10919653, 0.76416353, 0.84651841, 0.83696636]])

In [35]:
10*np.random.random((3,4))

array([[3.88045401, 9.98133142, 2.82138936, 5.2743289 ],
       [6.58755946, 4.83818228, 4.90563643, 7.27592853],
       [0.66668628, 9.86026368, 7.43385273, 9.08578022]])

In [49]:
a = np.floor(10*np.random.random((3,4)))
a

array([[9., 4., 6., 9.],
       [5., 9., 2., 4.],
       [2., 0., 1., 3.]])

In [50]:
a.shape

(3, 4)

In [51]:
a.ravel() #returns the arrray flattened

array([9., 4., 6., 9., 5., 9., 2., 4., 2., 0., 1., 3.])

In [52]:
a.reshape(6,2)

array([[9., 4.],
       [6., 9.],
       [5., 9.],
       [2., 4.],
       [2., 0.],
       [1., 3.]])

In [55]:
a.reshape(12,1)

array([[9.],
       [4.],
       [6.],
       [9.],
       [5.],
       [9.],
       [2.],
       [4.],
       [2.],
       [0.],
       [1.],
       [3.]])

In [57]:
a.reshape(12) # does same as ravel method

array([9., 4., 6., 9., 5., 9., 2., 4., 2., 0., 1., 3.])

In [58]:
a.shape

(3, 4)

In [65]:
a.T.shape #shape of the transposed ndarray

(4, 3)

In [66]:
#reshape does not change the size parmanently bu resize does

In [67]:
a.shape

(3, 4)

In [68]:
a.resize(2,6)

In [69]:
a.shape

(2, 6)

In [70]:
a.size

12

### Stacking arrays

In [72]:
a = np.floor(10*np.random.random((2,2)))
a

array([[1., 7.],
       [3., 3.]])

In [73]:
b = np.floor(10*np.random.random((2,2)))
b

array([[5., 5.],
       [9., 3.]])

In [75]:
np.stack((a,b))

array([[[1., 7.],
        [3., 3.]],

       [[5., 5.],
        [9., 3.]]])

In [76]:
np.vstack((a,b)) #verticle stack

array([[1., 7.],
       [3., 3.],
       [5., 5.],
       [9., 3.]])

In [78]:
np.hstack((a,b)) #horizontal stack

array([[1., 7., 5., 5.],
       [3., 3., 9., 3.]])

In [80]:
np.column_stack((a,b)) #same as hstack only for 2D

array([[1., 7., 5., 5.],
       [3., 3., 9., 3.]])

In [82]:
np.row_stack((a,b)) #same as vstack only for 2D

array([[1., 7.],
       [3., 3.],
       [5., 5.],
       [9., 3.]])

In [84]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [85]:
b = np.array([5,6,7,8])
b

array([5, 6, 7, 8])

In [86]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
np.column_stack((a,b)) # different from hstack()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [91]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
np.row_stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
np.r_[1:4,0,12] # creates numpy array

array([ 1,  2,  3,  0, 12])

In [111]:
np.c_[1:4]

array([[1],
       [2],
       [3]])

### Splitting arrays

In [112]:
a = np.floor(10*np.random.random((2,12)))
a

array([[9., 7., 7., 6., 1., 8., 6., 8., 9., 5., 0., 4.],
       [2., 9., 1., 1., 8., 1., 9., 9., 5., 5., 6., 5.]])

In [115]:
np.hsplit(a,3) #splits into 3 arrays for every one row

[array([[9., 7., 7., 6.],
        [2., 9., 1., 1.]]), array([[1., 8., 6., 8.],
        [8., 1., 9., 9.]]), array([[9., 5., 0., 4.],
        [5., 5., 6., 5.]])]

In [117]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[9., 7., 7.],
        [2., 9., 1.]]), array([[6.],
        [1.]]), array([[1., 8., 6., 8., 9., 5., 0., 4.],
        [8., 1., 9., 9., 5., 5., 6., 5.]])]

In [119]:
np.hsplit(a,(4,8))   # Split a after the fourth and the eighth column

[array([[9., 7., 7., 6.],
        [2., 9., 1., 1.]]), array([[1., 8., 6., 8.],
        [8., 1., 9., 9.]]), array([[9., 5., 0., 4.],
        [5., 5., 6., 5.]])]

In [120]:
a = np.floor(10*np.random.random((8,2)))
a

array([[6., 2.],
       [9., 6.],
       [1., 9.],
       [5., 3.],
       [2., 8.],
       [0., 4.],
       [3., 7.],
       [9., 9.]])

In [131]:
np.vsplit(a,(3,6))

[array([[6., 2.],
        [9., 6.],
        [1., 9.]]), array([[5., 3.],
        [2., 8.],
        [0., 4.]]), array([[3., 7.],
        [9., 9.]])]

In [132]:
np.vsplit(a,(3,2))

[array([[6., 2.],
        [9., 6.],
        [1., 9.]]), array([], shape=(0, 2), dtype=float64), array([[1., 9.],
        [5., 3.],
        [2., 8.],
        [0., 4.],
        [3., 7.],
        [9., 9.]])]

### Copies and Views

#### No Copy at All

In [185]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
b = a

In [187]:
b is a

True

In [188]:
b.shape

(10,)

In [189]:
a.shape

(10,)

In [190]:
id(a)

139921915665504

In [191]:
id(b)

139921915665504

### View or Shallow Copy¶

In [192]:
#Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [193]:
c = a.view()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
c is a

False

In [195]:
c is b

False

In [196]:
c.base is a

True

In [197]:
c.base is b

True

In [198]:
c.shape

(10,)

In [199]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
c[5] = 1001

In [201]:
c

array([   0,    1,    2,    3,    4, 1001,    6,    7,    8,    9])

In [202]:
a

array([   0,    1,    2,    3,    4, 1001,    6,    7,    8,    9])

### Deep Copy

In [203]:
#The copy method makes a complete copy of the array and its data.

In [204]:
d = c.copy() # a new array object with new data is created

In [205]:
c

array([   0,    1,    2,    3,    4, 1001,    6,    7,    8,    9])

In [206]:
d is c

False

In [207]:
d

array([   0,    1,    2,    3,    4, 1001,    6,    7,    8,    9])

In [208]:
#d.base = c #ERROR  d doesn't share anything

In [209]:
c[4] =100

In [210]:
c

array([   0,    1,    2,    3,  100, 1001,    6,    7,    8,    9])

In [211]:
d

array([   0,    1,    2,    3,    4, 1001,    6,    7,    8,    9])

In [222]:
np.empty(8) #random

array([9., 5., 0., 4., 5., 5., 6., 5.])

In [224]:
np.empty([2,2]) #random

array([[3., 7.],
       [9., 9.]])

In [225]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [227]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [228]:
np.repeat(x,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [230]:
np.repeat(x,2,axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [234]:
np.repeat(x,[2,4] , axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [235]:
np.repeat(x,[2,4] , axis = 1)

array([[1, 1, 2, 2, 2, 2],
       [3, 3, 4, 4, 4, 4]])

### “Automatic” Reshaping¶

In [236]:
a = np.arange(30)

In [237]:
a.shape = 2,-1,3  # -1 means "whatever is needed"

In [238]:
a.shape

(2, 5, 3)

In [239]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

### Vector Stacking

In [240]:
x = np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [242]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [244]:
np.vstack([x,y])

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [245]:
np.hstack([x,y])

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

#  **** ---   BREAK   ---  ****

### Linspace

In [254]:
np.linspace(1,10,6) # 6n numbers bw 1 to 10

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [256]:
np.linspace(1,10,6,endpoint = False)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [258]:
np.linspace(1,10,6, retstep = True)

(array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ]), 1.8)

### Logspace

In [266]:
np.logspace(1,2,4) # by default base=10

array([ 10.        ,  21.5443469 ,  46.41588834, 100.        ])

In [264]:
np.logspace(1,2,4,endpoint=False)

array([10.        , 17.7827941 , 31.6227766 , 56.23413252])

In [265]:
np.logspace(1,2,4,base = 2)

array([2.       , 2.5198421, 3.1748021, 4.       ])

### Identity

In [269]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Eye

In [271]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [281]:
np.eye(N = 3 ,k = -1,M =2)

array([[0., 0.],
       [1., 0.],
       [0., 1.]])

In [282]:
np.eye(N=4,M=6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### mgrid

In [284]:
np.mgrid[0:5]

array([0, 1, 2, 3, 4])

In [286]:
np.mgrid[0:5,0:4]

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [289]:
np.mgrid[0:5,0:4].shape

(2, 5, 4)

In [292]:
np.mgrid[0:3,5:7] # 2,3,2

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[5, 6],
        [5, 6],
        [5, 6]]])

In [293]:
np.mgrid[0:3,5:7].shape

(2, 3, 2)

In [290]:
np.mgrid[0:3,0:4,0:5] # 3,3,4,5 #advance

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2]]],


       [[[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3]],

        [[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3]],

        [[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3]]],


       [[[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]]]])

In [291]:
np.mgrid[0:3,0:4,0:5].shape

(3, 3, 4, 5)

### ogrid

In [294]:
np.ogrid[0:5,0:5]

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]])]

In [302]:
np.ogrid[-1:1:5j] #5j is a complex number

array([-1. , -0.5,  0. ,  0.5,  1. ])

### once

In [303]:
np.ones(4)

array([1., 1., 1., 1.])

In [309]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### ones_like

In [312]:
a = 10*np.random.random((3,4))
a

array([[8.74952427, 9.83741724, 5.68267726, 6.04533293],
       [1.270371  , 8.74536121, 5.02205515, 9.14871561],
       [2.47458102, 2.72601298, 5.55752461, 4.36353113]])

In [313]:
np.ones_like(a) #converts every value to 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### zeros

In [316]:
np.zeros(3)

array([0., 0., 0.])

In [318]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### zeros_like

In [320]:
a

array([[8.74952427, 9.83741724, 5.68267726, 6.04533293],
       [1.270371  , 8.74536121, 5.02205515, 9.14871561],
       [2.47458102, 2.72601298, 5.55752461, 4.36353113]])

In [322]:
np.zeros_like(a) # converts every value to 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [323]:
a

array([[8.74952427, 9.83741724, 5.68267726, 6.04533293],
       [1.270371  , 8.74536121, 5.02205515, 9.14871561],
       [2.47458102, 2.72601298, 5.55752461, 4.36353113]])

In [327]:
a.astype(int) #temporary

array([[8, 9, 5, 6],
       [1, 8, 5, 9],
       [2, 2, 5, 4]])

In [328]:
a

array([[8.74952427, 9.83741724, 5.68267726, 6.04533293],
       [1.270371  , 8.74536121, 5.02205515, 9.14871561],
       [2.47458102, 2.72601298, 5.55752461, 4.36353113]])

In [329]:
a = a.astype(int)

In [330]:
a

array([[8, 9, 5, 6],
       [1, 8, 5, 9],
       [2, 2, 5, 4]])

### atleast_1d

In [332]:
np.atleast_1d(3.4) 
#Scalar inputs are converted to 1-dimensional arrays, whilst higher-dimensional inputs are preserved.

array([3.4])

In [333]:
a

array([[8, 9, 5, 6],
       [1, 8, 5, 9],
       [2, 2, 5, 4]])

In [334]:
np.atleast_1d(a)

array([[8, 9, 5, 6],
       [1, 8, 5, 9],
       [2, 2, 5, 4]])

### atleast_2d 

In [336]:
a

array([[8, 9, 5, 6],
       [1, 8, 5, 9],
       [2, 2, 5, 4]])

In [337]:
np.atleast_2d(3.6) 
# View inputs as arrays with at least two dimensions.

array([[3.6]])

In [342]:
np.atleast_2d([1,2,34,4])

array([[ 1,  2, 34,  4]])

### atleast_3d

In [343]:
np.atleast_3d(2)

array([[[2]]])

In [344]:
np.atleast_3d([1,2,4])

array([[[1],
        [2],
        [4]]])

### mat (stands for matrix)

In [353]:
x = np.array([[1,2,4,5],[3,4,1,7]])
x

array([[1, 2, 4, 5],
       [3, 4, 1, 7]])

In [354]:
m = np.mat(x)

In [355]:
m

matrix([[1, 2, 4, 5],
        [3, 4, 1, 7]])

In [356]:
np.mat([1,2]) #converts 1D to 2D automatically

matrix([[1, 2]])

In [358]:
# np.mat([[[4]]])  ERROR -> matrix must be 3D

### Concatenation

In [367]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [369]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [372]:
np.concatenate((a,b)) # by default axis = 0

array([[1, 2],
       [3, 4],
       [5, 6]])

In [379]:
#np.concatenate((a,b),axis=1) # ERROR because for concatenation b has f
#different size i.e 1

In [380]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

### Diagonal

In [381]:
a

array([[1, 2],
       [3, 4]])

In [382]:
a.diagonal()

array([1, 4])

In [383]:
a.diagonal(1)

array([2])

In [384]:
a.diagonal(-1)

array([3])

In [391]:
a = 10*np.random.random((5,5))
a = a.astype(int)
a

array([[0, 7, 8, 9, 5],
       [2, 3, 0, 4, 2],
       [9, 8, 0, 4, 3],
       [3, 2, 6, 0, 7],
       [4, 4, 8, 6, 3]])

In [393]:
a.diagonal()

array([0, 3, 0, 0, 3])

In [394]:
a.diagonal(2)

array([8, 4, 3])

In [395]:
a.diagonal(1)

array([7, 0, 4, 7])

In [396]:
a.diagonal(-2)

array([9, 2, 8])

In [397]:
a.diagonal(-4)

array([4])

### dsplit

In [408]:
a = (10*np.random.random((2,2,4))).astype(int)
a

array([[[6, 4, 1, 9],
        [6, 7, 8, 8]],

       [[1, 2, 5, 3],
        [0, 5, 9, 9]]])

In [409]:
np.dsplit(a,2)

[array([[[6, 4],
         [6, 7]],
 
        [[1, 2],
         [0, 5]]]), array([[[1, 9],
         [8, 8]],
 
        [[5, 3],
         [9, 9]]])]

### dstack

In [415]:
a = np.array((1,2,3))
b = np.array((4,5,6))
a

array([1, 2, 3])

In [412]:
np.dstack((a,b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [414]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.stack((a,b))

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

### item

In [422]:
x = np.random.randint(9,size = (3,3))
x

array([[3, 8, 2],
       [3, 6, 6],
       [1, 5, 4]])

In [423]:
x.item(0)

3

In [424]:
x.item(6)

1

In [426]:
x.item((1,2))

6

### ravel

In [428]:
a = np.array([[12,3,4],[2,4,5]])
a

array([[12,  3,  4],
       [ 2,  4,  5]])

In [430]:
a.ravel() # converts ndarray to 1D array

array([12,  3,  4,  2,  4,  5])

### squeeze

In [435]:
a = np.array([[[1,2,3]]])
a

array([[[1, 2, 3]]])

In [437]:
np.squeeze(a)
#Remove single-dimensional entries from the shape of an array.

array([1, 2, 3])

In [439]:
np.squeeze(a).shape

(3,)

### swapaxes

In [444]:
a = np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [448]:
b = np.swapaxes(a,0,1) # swaps  axes 0 and 1
b

array([[1],
       [2],
       [3],
       [4]])

### take

In [453]:
a = np.array([1,2,3,4,5,6,2,7,8,8])
a

array([1, 2, 3, 4, 5, 6, 2, 7, 8, 8])

In [454]:
indices = [0,1,4]

In [455]:
np.take(a,indices) #returns numpy array , 'a' canbe list or numpy array

array([1, 2, 5])

### not

In [457]:
np.all([True,False])

False

In [458]:
np.all([True,True])

True

In [459]:
np.all([1,2,4])

True

In [462]:
np.all([1,2,True])

True

In [463]:
np.all([1,2,3,False])

False

In [464]:
np.all([1,2,3,True,False])

False

### any

In [465]:
np.any([True,False])

True

In [466]:
np.any([False])

False

In [467]:
np.any([1,2,True])

True

In [469]:
np.any([1,2,4,False])

True

### nonzero

In [470]:
x = np.array([[1,0,0], [0,2,0], [1,1,0]])
x

array([[1, 0, 0],
       [0, 2, 0],
       [1, 1, 0]])

In [472]:
np.nonzero(x) # returns 2 arrays that in together determines the position of the non zero elements

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

### where

In [473]:
np.where(True,1,2)

array(1)

In [474]:
a = [1,2,3,4]
b = [5,6,7,8]
c = [True,False,True,True]

In [476]:
np.where(c,a,b) # if c is True then a is selected otherwise b is selected

array([1, 6, 3, 4])

### argmax

In [479]:
a = np.array([2,4,12,3,6])
a

array([ 2,  4, 12,  3,  6])

In [482]:
np.argmax(a) #returns index of maximum element
#In case of multiple occurrences of the maximum values, the indices corresponding to the first occurrence are returned.

2

### argmin

In [483]:
a

array([ 2,  4, 12,  3,  6])

In [493]:
a.argmin() #same as np.argmin(a)

0

In [485]:
np.argmin(a) # returns index of minimum element

0

### argsort

In [486]:
a

array([ 2,  4, 12,  3,  6])

In [487]:
np.argsort(a)
#Returns the indices that would sort an array.

array([0, 3, 1, 4, 2])

### max

In [488]:
a

array([ 2,  4, 12,  3,  6])

In [489]:
np.max(a) #max element

12

### min

In [490]:
a

array([ 2,  4, 12,  3,  6])

In [492]:
np.min(a)

2

### ptp ???

In [503]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [501]:
np.ptp(x,axis =0)

array([1, 2, 0])

In [502]:
np.ptp(x,axis = 1)

array([1, 2, 1])

### searchsorted

In [505]:
np.searchsorted([12,3,4,5,6,7,8],4) # binary search

2

In [506]:
np.searchsorted([12,3,4,5,6,7,8],4,side = "right")

3

### sort

In [509]:
a = np.array([[1,3,2],[4,2,5]])
a

array([[1, 3, 2],
       [4, 2, 5]])

In [510]:
np.sort(a)

array([[1, 2, 3],
       [2, 4, 5]])

In [511]:
a = np.array([1,5,2,3,2])
a

array([1, 5, 2, 3, 2])

In [513]:
np.sort(a)

array([1, 2, 2, 3, 5])

### choose

In [518]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13],[4,5,6,8],
           [20, 21, 22, 23], [30, 31, 32, 33]]

In [520]:
np.choose([2, 3, 1, 0], choices)
# 1st element from 2 ,2nd from 3, 3rd from 1, 4rth from 0

array([ 4, 21, 12,  3])

### compress

In [527]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [530]:
np.compress([0,1],a,axis = 0)
#Return selected slices of an array along given axis.

array([[4, 5, 6]])

In [533]:
np.compress([True,False,False],a,axis = 0)

array([[1, 2, 3]])

In [534]:
np.compress([True,False,False],a,axis = 1)

array([[1],
       [4],
       [7]])

### cumprod

In [538]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [540]:
np.cumprod(a) # value*(index-1)

array([ 1,  2,  6, 24])

In [543]:
a = np.array([[1,2,3,8,9]])
a

array([[1, 2, 3, 8, 9]])

In [544]:
np.cumprod(a)

array([  1,   2,   6,  48, 432])

### cumsum

In [545]:
a

array([[1, 2, 3, 8, 9]])

In [546]:
np.cumsum(a)

array([ 1,  3,  6, 14, 23])

### inner

In [555]:
 a = np.array([1,2,3])

In [558]:
b = np.array([0,1,4])

In [561]:
np.inner(a,b) # sum of product of 2 arrays

14

### fill

In [562]:
a

array([1, 2, 3])

In [565]:
a.fill(0)

In [566]:
a

array([0, 0, 0])

### imag

In [3]:
a = np.array([1+2j,4+6j])
a.imag

array([2., 6.])

In [4]:
a = np.array([2+5j,6])
a.imag

array([5., 0.])

### real

In [14]:
a = np.array([2+3j,5+5j])
a

array([2.+3.j, 5.+5.j])

In [15]:
a.real

array([2., 5.])

In [16]:
a = np.array([3+6j,6])
a

array([3.+6.j, 6.+0.j])

In [17]:
a.real

array([3., 6.])

### put

In [6]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
np.put(a,[0,4],[1001,1002])
a

array([1001,    2,    3,    4, 1002])

### putmask

In [9]:
a

array([1001,    2,    3,    4, 1002])

In [11]:
np.putmask(a,a>100,a+2000)
a

array([3001,    2,    3,    4, 3002])

In [13]:
np.putmask(a,a>3000,True) #converted True to 1
a

array([1, 2, 3, 4, 1])

### sum

In [19]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [20]:
np.sum(a)

15

In [21]:
a.sum()

15

### cov  (covariance)

In [23]:
x = np.array([[0, 2], [1, 1], [2, 0]])
x

array([[0, 2],
       [1, 1],
       [2, 0]])

In [24]:
np.cov(x)

array([[ 2.,  0., -2.],
       [ 0.,  0.,  0.],
       [-2.,  0.,  2.]])

## Linear Algebra

In [25]:
x = [1, 2, 3]
y = [4, 5, 6]

### cross

In [27]:
np.cross(x,y)

array([-3,  6, -3])

### dot

In [29]:
np.dot(x,y)

32

In [30]:
np.linspace(-2,2,5)

array([-2., -1.,  0.,  1.,  2.])

In [31]:
np.outer(5,np.linspace(-2,2,5))

array([[-10.,  -5.,   0.,   5.,  10.]])

In [37]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.outer(5*np.ones(3),np.linspace(-2,2,5))

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

### vdot

In [39]:
a = np.array([1+2j])
b = np.array([5+6j])  # 17 = (i1 * i2) + (j1 * j2)
np.vdot(a,b)          # -4 = j2 - j1

(17-4j)

In [40]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a,b)

(70-8j)